services:
  server:
    container_name: backend-django-v2           # Nombre del contenedor
    image: jh3re404/backend-django-fuzzy-ehr-server:v2 # Nombre y tag de la imagen
    build:
      context: .                                # Ruta al directorio donde está el Dockerfile
    environment:
      DATABASE_URL: "file:./dev.db" 
    ports: 
      - '8000:8000'
