# Generated by Django 5.1.3 on 2024-11-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cie_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cie_codes', models.ManyToManyField(to='diagnoses.disease')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisGroupProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_level', models.FloatField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.diagnosis')),
                ('disease_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.diseasegroup')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='groups',
            field=models.ManyToManyField(through='diagnoses.DiagnosisGroupProbability', to='diagnoses.diseasegroup'),
        ),
        migrations.CreateModel(
            name='GroupSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.IntegerField()),
                ('disease_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.diseasegroup')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.diagnosis')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.ManyToManyField(through='diagnoses.DiagnosisSymptom', to='diagnoses.symptom'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='vital_signs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnoses.vitalsigns'),
        ),
    ]
